name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: List current directory contents
      run: ls -la
    - name: Build the Docker image
      run: docker build . --file pt112-tf29-jax0314-py39/Dockerfile --tag gradient-base-container:$(date +%s)
